---
title: "Module 2 Report"
author: '450132759 / 450463055'
date: "August 28, 2018"
output: 
  prettydoc::html_pretty:
    theme: cayman # prettydoc theme
    highlight: option # syntax highlighting
    css: custom.css # custom css file to change font family and size
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

## Importing Data

```{r import}
library(tidyverse)
survey = readr::read_csv("survey.csv")
```

## Fix column names
TODO: Change the postcode to char, does not make sense to compare postcode by their values.
```{r}
old_names = colnames(survey)
new_names = c("timestamp", "id", "gender", "postcode", "intro_stat", "clubs",
                     "study_time", "social_media", "siblings", "pet", "live_with_parents",
                     "exercise_time", "eye_colour", "work_time", "fav_season","shoe_size",
                     "height")
colnames(survey) = new_names # Overwrite with new names
names(new_names) = old_names
new_names
```

## Eye color
```{r}
survey$eye_colour <- tolower(survey$eye_colour) # change all names to lowercase
survey$eye_colour = stringr::str_to_title(survey$eye_colour) # Capitalize first letter of every word
survey$eye_colour <- forcats::fct_lump(survey$eye_colour, n = 6) # preserve the 6 most common eye colours, and converts the smaller categories to a 'other' category
ggplot(survey, aes(x = eye_colour)) + 
  geom_bar(fill = c("black","blue","brown2","brown4",
                    "green3","darkgoldenrod3","red")) + 
  labs(title = names(new_names[new_names == "eye_colour"]),
       y = "Count", x = "Eye colour") + 
  theme_linedraw() + coord_flip()
```

## Gender 
```{r}
# survey$gender <- toupper(survey$gender)
# survey$gender <- substr(survey$gender, start = 1, stop = 1)
# survey$gender <- forcats::fct_lump(survey$gender, n = 2)
# table(survey$gender)
survey = survey %>%
  dplyr::mutate(gender = toupper(gender),
         gender = substr(gender, start = 1, stop = 1),
         gender = forcats::fct_lump(gender, n=2))
table(survey$gender)
```

### Social Media
```{r}
survey$social_media = tolower(survey$social_media)
survey$social_media = forcats::fct_recode(survey$social_media,
  "facebook" = "facebook messenger",
  "facebook" = "messenger",
  "instagram" = "instgram",
  "instgram" = "ins",
  "none" = "no",
  "none" = "n/a"
)
survey$social_media = forcats::fct_lump(survey$social_media, n=7)
table(survey$social_media)
```


## Height

```{r}
survey = survey %>%
  mutate(height = 
    case_when(
      height < 3 ~ height * 100,
      height < 10 ~ height * 30.48,
      height > 250 ~ NA_real_,
      TRUE ~ height # otherwise keep the same values
    )
  ) # case_when() excexutes a series of if-else statements
sort(survey$height)
ggplot(survey, aes(y = height, x = gender)) + 
  geom_boxplot() + 
  theme_linedraw() + 
    labs(title = names(new_names[new_names == "height"]),
       x = "Gender", y = "Height (cm)")
```

## Exporting the cleaned data

```{r}
readr::write_csv(survey, "survey_cleaned.csv")
```


